version: '2'

services:
  app:
    build: .
    image: blogway
    command: amber watch
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/blogway_development
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - .:/app
      - nodes:/app/node_modules
      - shards:/app/lib

  test:
    build: .
    image: blogway
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && amber db drop create migrate'
    environment:
      AMBER_ENV: test
      DATABASE_URL: postgres://admin:password@db:5432/blogway_test
    links:
      - db
    volumes:
      - .:/app

  migrate:
    build: .
    image: blogway
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && amber db migrate seed'
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/blogway_development
    volumes:
      - .:/app
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogway_development
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db:
  nodes:
  shards:
